unepwcmc/go-fox

.travis.yml, app/controllers/surveys_controller.rb, config/database.yml.travis, config/secrets.yml.travis, test/controllers/surveys_controller_test.rb, test/factories/surveys.rb, test/factories/user.rb
Opening up a PR so that @spencerldixon can comment as I go along with trying to fix the tests.
=> Fix survey tests

app/models/survey.rb, db/schema.rb, db/seeds.rb, test/factories/surveys.rb, test/models/survey_test.rb
Opening a PR so that @spencerldixon can see the code as I develop this branch further and make comments if necessary.
=> Add database seeds

app/controllers/demographic_questions_controller.rb, app/controllers/questions_controller.rb, app/views/demographic_questions/index.html.erb, app/views/questions/index.html.erb, config/routes.rb, test/controllers/demographic_questions_controller_test.rb, test/controllers/questions_controller_test.rb
Initial work towards removing destroy functionality for questions and demographic questions.
=> Remove destroy for questions and demographic questions

app/controllers/responses_controller.rb, test/controllers/responses_controller_test.rb
Initial work towards testing for the responses controller.
=> Tests for responses

app/assets/javascripts/application.js, app/assets/javascripts/response.coffee, app/assets/stylesheets/application.css, app/controllers/responses_controller.rb, app/javascript/components/DemographicQuestion.js, app/javascript/components/MultiSelectQuestion.js, app/models/classification.rb, app/models/demographic_question.rb, app/models/option.rb, app/models/question.rb, app/models/survey.rb, app/views/responses/_form.html.erb, db/seeds.rb, package.json, test/factories/classifications.rb, test/factories/demographic_questions.rb, test/factories/options.rb, test/factories/questions.rb, test/factories/surveys.rb, test/models/classification_test.rb, test/models/demographic_question_test.rb, test/models/option_test.rb, test/models/question_test.rb, test/models/survey_test.rb, yarn.lock
Initial work in progress towards adding multiple select questions.
=> Add multiple select

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_table.scss, app/assets/stylesheets/components/_title-bar.scss, app/assets/stylesheets/utilities/_base.scss, app/assets/stylesheets/utilities/_helpers.scss, app/views/layouts/application.html.erb, app/views/responses/index.html.erb, app/views/surveys/index.html.erb
First pass at survey results page.
@spencerldixon csv download needs adding - i've added it to the Trello card.
Need clarification on what the one -> in the design points to for each row in the table. Left both links in for now.
=> Survey result list

app/assets/stylesheets/components/_buttons.scss, app/views/responses/index.html.erb, app/views/responses/show.html.erb, app/views/surveys/index.html.erb
When logged in as a normal user
- Tweak text on some of the buttons and titles
- Added a wrapper around the full response page
=> User pages

app/assets/stylesheets/components/_block.scss, app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/utilities/_base.scss, app/assets/stylesheets/utilities/_helpers.scss, app/views/responses/results.html.erb, config/locales/en.yml
Add basic styling and placeholder content on the results page.
Outstanding work
- Chart
- Filters
=> Add basic layout for the results page

app/views/admin/responses/index.html.erb, app/views/global_admin/_cta_edit_account.html.erb, app/views/responses/index.html.erb
When logged in as an admin
- The responses list page has been styled http://localhost:3000/admin/responses/
=> Admin survey results

app/views/devise/registrations/new.html.erb
Initial work to fix the sign up bug. Please test by creating a new user account and submitting new credentials, which have not already been used locally.
=> Initial work to fix the sign up bug

app/controllers/static_pages_controller.rb, app/views/global_public/_nav_primary.html.erb, app/views/static_pages/about_go_fox.html.erb, app/views/static_pages/legal.html.erb, app/views/static_pages/support.html.erb, config/routes.rb
Initial work to add the additional pages. Only the titles have been changed. We are using the same dummy text in each page still.
The new pages are:
- Support
- Legal
- About Go-Fox
These will be completed at a later date, but it was necessary to add these pages just for now.
=> Initial work to add additional pages

db/seeds.rb
This is the initial work to add a new demographic question quoted below:
"If there are any issues which you think are relevant to debates about the future of conservation, which were not included in this survey, please briefly outline them below. We intend to incorporate new statements into the survey in the future, so your suggestions are very welcome."
You will need to run this command below to populate this new demographic question:
`rails db:seed`
=> Initial work to add new demographic question

db/seeds.rb
This is the initial work to make the new demographic question optional.
=> Make new demographic question optional

app/views/admin/users/index.html.erb
This is the initial work to display the organisational type on the admin users page:
- (o) is organisational
- (e) is educational
This is fairly simplistic for now.
=> Display the organisational type on the admin users page

app/controllers/admin/dashboard_controller.rb, app/controllers/admin/users_controller.rb, app/jobs/csv_user_exporter_job.rb, app/mailers/application_mailer.rb, app/views/admin/users/_export_form.html.erb, app/views/admin/users/index.html.erb, config/routes.rb, lib/modules/csv_user_exporter.rb
This is the initial support for the CSV download of users on the admin dashboard. Please make sure you have the correct environment variables set for example, `MAILER_HOST` should be `localhost:3000` in your `.env` file.
=> Csv download option for list of users

Capfile, Gemfile, Gemfile.lock
This is the initial work to add Sidekiq support to Capistrano within the Go-Fox project.
=> Add the configuration for sidekiq in capistrano

Capfile, Gemfile, Gemfile.lock, config/appsignal.yml, lib/modules/csv_exporter.rb
This is the initial work to add AppSignal support on Go-Fox, which apparently has fixed the CSV export bug on staging!
=> Add appsignal

app/views/admin/responses/index.html.erb
This is the initial work to add the score to the all survey responses page. The frontend will need to be adjusted later.
=> Add score to all survey responses page

app/views/global_admin/_nav.html.erb, app/views/global_public/_footer.html.erb
This is the initial work to:
- Hide the classifications link for now, but not remove them,
- Add login link to organisational and educational users.
=> Fixes to links

lib/modules/csv_exporter.rb
This is the initial work to fix the CSV export bug which was occuring for the CSV export of all survey responses. This code now works fine for both:
- Single survey CSV export
- All surveys CSV export
I have also tested in the case of there being just one Customised Question and the rest of the fields are correctly populated with "n/a" where appropriate.
=> Fix csv export for all results

app/views/global_public/_topbar.html.erb
Hide log in button from nav on FoC side pages
=> remove foc-side login

app/javascript/admin.js, app/javascript/helpers/application-helpers.js, app/views/devise/registrations/new.html.erb
Add data-prevent-default-enter to forms to prevent enter keydown triggering submit
=> prevent submitting on enter click on sign up form

app/assets/stylesheets/components/_full-response.scss, app/assets/stylesheets/components/form/_form.scss, app/controllers/surveys_controller.rb, app/views/responses/show.html.erb, app/views/surveys/_form.html.erb, app/views/surveys/edit.html.erb, app/views/surveys/new.html.erb, app/views/surveys/show.html.erb
Small styling changes & handling current_user == nil
=> Frontend tweaks

app/views/surveys/_educational_fields.html.erb
This is the initial work to fix a few issues on the educational fields partial. This prevents a crash when you try to create a new survey as an educational user.
=> Fix issues with educational fields partial

app/assets/javascripts/response.coffee, app/views/surveys/_customised_question_fields.html.erb, app/views/surveys/_form.html.erb, app/views/surveys/_option_fields.html.erb
hide add option/question button when max reached when creating a survey
=> hide add option/question button when max reached

app/views/demographic_questions/show.html.erb, app/views/questions/show.html.erb
use globalise so current locale isn't changed outside of the text fields
=> use globalise so current locale isn't changed outside of the text fields

app/assets/stylesheets/components/_table.scss, app/views/admin/users/index.html.erb, app/views/demographic_questions/edit.html.erb, app/views/demographic_questions/index.html.erb, app/views/demographic_questions/new.html.erb, app/views/demographic_questions/show.html.erb, app/views/questions/edit.html.erb, app/views/questions/index.html.erb, app/views/questions/new.html.erb, app/views/questions/show.html.erb
Hide links to add new questions
Add padding to question tables
Add page containers to question edit/new/show actions
=> hide new question links and touch up styling

app/javascript/helpers/pagination-helpers.js, app/views/global_admin/_total_results.html.erb
Check if on last page for page indices and if so add all remaining questions
Sneaky quick style fix to header
=> Pagination fix

app/assets/stylesheets/components-vue/chart.scss, app/assets/stylesheets/components/_results.scss, app/views/responses/results.html.erb
remove classification from results chart and fix stlying in ie
=> remove classification from results chart and fix stlying in ie

app/views/layouts/application.html.erb, app/views/shared/_google_analytics.html.erb
This is the initial work towards adding Google Analytics when in production.
=> Initial support for google analytics

app/views/admin/responses/index.html.erb
This is the initial work to replace the organistaion with the survey title on the admin responses page
=> Initial work to replace organisation with survey title on admin responses

app/views/devise/registrations/new.html.erb, app/views/global/_sign_up_warning.html.erb, config/locales/en.yml
This is the initial work to add the sign up warning modal.
=> Initial work to add sign up warning modal

app/helpers/responses_helper.rb, app/views/admin/responses/index.html.erb, app/views/responses/index.html.erb
add response scores helper
add responses to views/responses/index.html.erb
=> Response scores

app/assets/stylesheets/components-vue/chart.scss, app/assets/stylesheets/components/_box.scss, app/assets/stylesheets/components/_results.scss, app/assets/stylesheets/utilities/_variables.scss, app/javascript/components/chart/ChartResults.vue, app/views/responses/results.html.erb, config/locales/en.yml
Make chart page responsive and add legend (and remove filters)
=> Results page

app/assets/javascripts/response.coffee, app/models/survey.rb, app/views/surveys/_form.html.erb, test/controllers/surveys_controller_test.rb
This is the initial work to permit at most three customised questions, as per the request of the client.
=> Initial work to allow up to three customised questions

app/helpers/responses_helper.rb, app/models/demographic_question.rb, app/views/responses/_form.html.erb
This adds a check for customised questions for putting in an *
P.S. To make testing locally easier making this change to PaginationButton.vue will let you skip through pages without filling out every question!
```
// if (this.$store.state.pagination.errors == 0) { this.newPage(page) }
this.newPage(page)
```
=> show * for all customised questions

app/views/responses/results.html.erb
Forgot to change the variable names in the view!
=> Design edits

config/deploy.rb, config/deploy/production.rb
Here are the new production server details for go-fox
=> New production server details

config/deploy.rb, config/deploy/staging.rb
=> new staging server details

app/assets/stylesheets/components-vue/_progress-bar.scss, app/assets/stylesheets/components-vue/_v-select.scss, app/assets/stylesheets/components/form/_form.scss, app/controllers/responses_controller.rb, app/javascript/admin.js, app/javascript/components/form_fields/MultipleSelectBox.vue, app/javascript/components/form_fields/VMultiselect.vue, app/javascript/helpers/custom-polyfills.js, app/javascript/helpers/focus-helpers.js, app/javascript/mixins/mixin-focus-capture.js, app/javascript/mixins/mixin-popup-close-listeners.js, config/deploy/staging.rb
Stops the progress bar being cut off. There is still a tiny bit of cut-off on the final page as the svg itself has a little bit missing, but it's less than before, so may be fine.
The order of the chart data is also reversed so that the current user line is added last.
Add custom multiselect - need to make double sure this links up fine with the backend (I tested with one survey response and it seemed ok)
=> Design tweaks

app/models/classification.rb, app/models/customised_question.rb, app/models/demographic_question.rb, app/models/option.rb, app/models/question.rb, app/models/survey.rb, config/deploy/staging.rb, db/migrate/20190621104229_change_published_for_surveys.rb, db/schema.rb, test/factories/classifications.rb, test/factories/customised_questions.rb, test/factories/demographic_questions.rb, test/factories/options.rb, test/factories/questions.rb, test/factories/surveys.rb, test/models/classification_test.rb, test/models/customised_question_test.rb, test/models/demographic_question_test.rb, test/models/option_test.rb, test/models/question_test.rb, test/models/survey_test.rb
This PR is the initial work to set the default checked published boolean.
=> Initial work to set the default published boolean to true for the newly created surveys

app/views/surveys/_educational_fields.html.erb, app/views/surveys/_form.html.erb, app/views/surveys/_organisational_fields.html.erb
Text and label changes.
Hiding some questions.
=> More minor fixes

.travis.yml, config/locales/en.yml
This is the initial work to fix the links for the powerpoint presentations and pdf resources.
=> Fix links for powerpoint presentations and pdf resources
